class AgentDefinition {
  final String id;
  final String name;
  final String layer;
  final String description;

  const AgentDefinition(this.id, this.name, this.layer, this.description);
}

class AgentRegistry {
  static const _core = <AgentDefinition>[
    AgentDefinition('muwajjih','الموجّه','التوجيه','تحليل النية وبناء خطة التنفيذ'),
    AgentDefinition('damj','الدمج','التوجيه','دمج نتائج الوكلاء والتحقق من الاتساق'),
    AgentDefinition('muraqib','المراقب','التوجيه','مراقبة التنفيذ والأخطاء'),
    AgentDefinition('ayaat','آيات','القرآن','استرجاع الآيات من الفهرس المحلي'),
    AgentDefinition('tafsir','تفسير','القرآن','تحليل دلالي قائم على المصادر المحلية'),
    AgentDefinition('jummal','جُمّل','القرآن','الحسابات العددية للنص'),
    AgentDefinition('adadi','عددي','القرآن','حساب المؤشرات العددية المعلنة'),
    AgentDefinition('rabet','رابط','القرآن','ربط النتائج بالمحاور المعرفة محلياً'),
    AgentDefinition('siyaq','سياق','القرآن','فحص السياق النصي المحيط'),
    AgentDefinition('taamul','تأمل','القرآن','صياغة أسئلة تأملية'),
    AgentDefinition('tibyan','تبيان','القرآن','تحليل الكلمات الغريبة'),
    AgentDefinition('tadabbur','تدبر','القرآن','استخراج مسارات تدبرية'),
    AgentDefinition('qiraat','قراءات','القرآن','عرض بيانات القراءات المتاحة'),
    AgentDefinition('falak','فلك','الكون','تحليل المصطلحات الفلكية'),
    AgentDefinition('tanjim','تنجيم','الكون','فهرسة الإشارات الفلكية'),
    AgentDefinition('physics','فيزياء','الكون','تحليل المصطلحات الفيزيائية'),
    AgentDefinition('tibb','طب','الكون','فهرسة الإشارات الطبية دون تشخيص'),
    AgentDefinition('nafs','نفس','الكون','تحليل مفردات النفس'),
    AgentDefinition('hayat','حياة','الكون','تحليل مفردات الحياة'),
    AgentDefinition('ard','أرض','الكون','تحليل مفردات الأرض'),
    AgentDefinition('hisab','حساب','الكون','حساب المؤشرات العددية'),
    AgentDefinition('handasa','هندسة','الكون','تحليل البنى الهندسية النصية'),
    AgentDefinition('tarikh','تاريخ','الكون','فهرسة الإشارات التاريخية'),
    AgentDefinition('tafkir','تفكير','الإدراك','تنظيم مسار التفكير'),
    AgentDefinition('falsafa','فلسفة','الإدراك','تحليل الأسئلة الفلسفية'),
    AgentDefinition('mantiq','منطق','الإدراك','فحص بنية الاستدلال'),
    AgentDefinition('kalam','كلام','الإدراك','تصنيف المسائل العقدية'),
    AgentDefinition('akhlaq','أخلاق','الإدراك','تحليل القيم الأخلاقية'),
    AgentDefinition('ijtima','اجتماع','الإدراك','تحليل المفاهيم الاجتماعية'),
    AgentDefinition('siyasa','سياسة','الإدراك','تحليل المفاهيم السياسية'),
    AgentDefinition('figh','فقه','الإدراك','فهرسة المفاهيم الفقهية'),
    AgentDefinition('iqtisad','اقتصاد','الإدراك','تحليل المفاهيم الاقتصادية'),
    AgentDefinition('fan','بلاغة','الإدراك','تحليل الأساليب البلاغية'),
    AgentDefinition('sawt','صوت','الصوت','تحليل النصوص المرتبطة بالصوت'),
    AgentDefinition('tiry al','تلاوة','الصوت','تنظيم بيانات التلاوة المتاحة'),
    AgentDefinition('shifa_sound','صوت علاجي','الصوت','فهرسة الادعاءات الصوتية دون اعتمادها كحقائق'),
    AgentDefinition('tawatur','تواتر','الصوت','تحليل تكرار الأنماط'),
    AgentDefinition('iqa','إيقاع','الصوت','تحليل الإيقاع النصي'),
    AgentDefinition('nur','نور','الرؤية','تحليل مفردات النور'),
    AgentDefinition('lawh','لوح','الرؤية','تحليل البنى البصرية الموصوفة'),
    AgentDefinition('sadeem','سديم','الرؤية','تحليل المصطلحات الكونية'),
    AgentDefinition('dhahab','ذهب','الرؤية','تحليل الأنماط العددية'),
    AgentDefinition('ruya','رؤية','الرؤية','دمج النتائج البصرية المتاحة'),
    AgentDefinition('tadrib','تدريب','التدريب','إدارة دورات التدريب المحلية'),
    AgentDefinition('tahsin','تحسين','التدريب','إدارة تحسين النموذج عند توفر مسار تدريب حقيقي'),
    AgentDefinition('tasdir','تصدير','التدريب','إدارة تصدير النماذج المدعوم'),
    AgentDefinition('ikhtibar','اختبار','التدريب','تشغيل اختبارات التحقق'),
    AgentDefinition('taghziya','تغذية','التدريب','إدارة مصادر البيانات المحلية'),
    AgentDefinition('tashfir','تشفير','الأمان','إدارة العمليات المشفرة المدعومة'),
    AgentDefinition('hisar','حصار','الأمان','فرض حدود التنفيذ'),
    AgentDefinition('naskh_backup','نسخ احتياطي','الأمان','إدارة النسخ المحلية'),
    AgentDefinition('tawthiq','توثيق','الأمان','إدارة التحقق المحلي'),
    AgentDefinition('lamarkazi','لامركزي','الأمان','إدارة الاتصالات اللامركزية المدعومة'),
    AgentDefinition('jiro','جيرو','المستشعرات','قراءة الجيروسكوب عند التصريح'),
    AgentDefinition('mikrofon','ميكروفون','المستشعرات','إدارة إدخال الصوت عند التصريح'),
    AgentDefinition('idaa','إضاءة','المستشعرات','قراءة الإضاءة عند التصريح'),
    AgentDefinition('nabd','نبض','المستشعرات','قراءة الحساس المدعوم عند التصريح'),
    AgentDefinition('asrar_maknuna','أسرار مكنونة','الأسرار','بحث نصي منضبط في المعرفة المحلية'),
    AgentDefinition('khabir','خبير','الأسرار','تحليل النتائج المحلية'),
    AgentDefinition('adham','أدهم','الأسرار','فهرسة المصطلحات المعرفة'),
    AgentDefinition('sajid','ساجد','الأسرار','فهرسة آيات السجود'),
    AgentDefinition('tabattul','تبتل','الأسرار','تحليل المفردات ذات الصلة'),
    AgentDefinition('tafsil','تفصيل','الأسرار','تفصيل نتائج البحث'),
    AgentDefinition('siyaq_harfi','سياق حرفي','الأسرار','تحليل السياق الحرفي'),
    AgentDefinition('mutashabih','متشابه','الأسرار','البحث عن التشابه النصي'),
    AgentDefinition('tanzil_mutlaq','تنزيل','الأسرار','فهرسة المصطلحات ذات الصلة'),
    AgentDefinition('kitab_ard','كتاب الأرض','الأسرار','تحليل إشارات الأرض'),
    AgentDefinition('kitab_samaa','كتاب السماء','الأسرار','تحليل إشارات السماء'),
    AgentDefinition('shifrat','شفرات','الأسرار','تحليل الأنماط القابلة للحساب فقط'),
    AgentDefinition('wahy','وحي','الأسرار','فهرسة المفردات دون ادعاء كشف الوحي'),
    AgentDefinition('ruh','روح','الأسرار','فهرسة المفردات المتعلقة بالروح'),
    AgentDefinition('bath','بعث','الوجود','تحليل مفردات البعث'),
    AgentDefinition('mawt','موت','الوجود','تحليل مفردات الموت'),
    AgentDefinition('layl','ليل','الوجود','فهرسة مفردات الليل'),
    AgentDefinition('nahar','نهار','الوجود','فهرسة مفردات النهار'),
    AgentDefinition('shams','شمس','الوجود','فهرسة مفردات الشمس'),
    AgentDefinition('qamar','قمر','الوجود','فهرسة مفردات القمر'),
    AgentDefinition('kawakib','كواكب','الوجود','فهرسة مفردات الكواكب'),
    AgentDefinition('istinbat','استنباط','الوجود','تنظيم الاستنباط القابل للتتبع'),
    AgentDefinition('furqan','فرقان','الوجود','فهرسة المفاهيم'),
    AgentDefinition('dhikr','ذكر','الوجود','فهرسة الذكر'),
    AgentDefinition('kitab','كتاب','الوجود','فهرسة الكتاب'),
    AgentDefinition('injil','إنجيل','الوجود','فهرسة الإشارات'),
    AgentDefinition('ilm_makhfi','علم مخفي','الفكر العميق','تحليل الاستعلامات العميقة'),
    AgentDefinition('mufakkir','مفكر','الفكر العميق','توسيع زوايا التحليل'),
    AgentDefinition('darb_amthal','أمثال','الفكر العميق','فهرسة الأمثال'),
    AgentDefinition('mantiq_tayr','منطق الطير','الفكر العميق','تحليل الإشارات'),
    AgentDefinition('ilm_sana','علم الصنعة','الفكر العميق','فهرسة المفاهيم'),
    AgentDefinition('nashah_ula','النشأة الأولى','الفكر العميق','تحليل المفردات'),
    AgentDefinition('ilm_kitab','علم الكتاب','الفكر العميق','فهرسة النتائج'),
    AgentDefinition('zubur','زبور','الفكر العميق','فهرسة الإشارات'),
    AgentDefinition('suhuf_ula','صحف أولى','الفكر العميق','فهرسة الإشارات'),
    AgentDefinition('alwah','ألواح','الفكر العميق','فهرسة الإشارات'),
    AgentDefinition('bashar_aql','بشر وعقل','الوعي الذاتي','مراجعة الفرضيات'),
    AgentDefinition('limadha','لماذا','الوعي الذاتي','توليد أسئلة السبب والنتيجة'),
    AgentDefinition('mudarrib_dhati','مدرب ذاتي','الوعي الذاتي','تنظيم مراجعات الأداء'),
    AgentDefinition('la_takhudhuhu_sina','يقظة','الأعلى','مراقبة حالة النظام'),
    AgentDefinition('mudabbir_ala','الوعي الجامع','الأعلى','دمج مسارات التنفيذ'),
    AgentDefinition('grammar','نحو','لغة','تحليل نحوي'),
    AgentDefinition('rhetoric','بلاغة','لغة','تحليل بلاغي'),
    AgentDefinition('semantic','دلالة','لغة','تحليل دلالي'),
    AgentDefinition('philosophy','فلسفة','لغة','تحليل فلسفي'),
    AgentDefinition('ultra_deep_0','عمق 0','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_1','عمق 1','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_2','عمق 2','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_3','عمق 3','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_4','عمق 4','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_5','عمق 5','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_6','عمق 6','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_7','عمق 7','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_8','عمق 8','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('ultra_deep_9','عمق 9','فائقة العمق','مسار تحليل عميق'),
    AgentDefinition('planner','مخطط','التشغيل','تحويل الطلب إلى خطة قابلة للتنفيذ'),
    AgentDefinition('critic','ناقد','التشغيل','مراجعة نتائج الوكلاء قبل الدمج'),
    AgentDefinition('researcher','باحث','التشغيل','تنظيم البحث في المصادر المحلية'),
    AgentDefinition('verifier','متحقق','التشغيل','التحقق من اكتمال النتائج'),
    AgentDefinition('formatter','منسق','المخرجات','تهيئة النتائج بصيغ العرض'),
    AgentDefinition('artifact','مُخرج','المخرجات','إدارة المخرجات والملفات'),
    AgentDefinition('exporter','مصدّر','المخرجات','تنفيذ صيغ التصدير المدعومة'),
    AgentDefinition('memory','ذاكرة','التشغيل','إدارة سياق الجلسة المحلي'),
    AgentDefinition('safety','أمان','التشغيل','فرض حدود التنفيذ المحلي'),
    AgentDefinition('scheduler','مجدول','التشغيل','إدارة المهام المؤجلة المحلية'),
    AgentDefinition('evaluator','مقيّم','التدريب','قياس الأداء من بيانات حقيقية'),
    AgentDefinition('retriever','مسترجع','التشغيل','استرجاع المعرفة المفهرسة'),
    AgentDefinition('context','سياق جامع','التشغيل','تجميع السياق للوكيل'),
    AgentDefinition('narrator','صائغ','المخرجات','صياغة النتيجة النهائية'),
  ];

  static List<AgentDefinition> get all => List.unmodifiable(_core);
  static AgentDefinition? byId(String id) {
    for (final a in _core) { if (a.id == id) return a; }
    return null;
  }
}
